# Generated by Django 3.1.2 on 2020-10-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_left_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('top_left_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('bot_right_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('bot_right_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
