# Generated by Django 3.1.2 on 2020-10-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eddies', '0002_auto_20201016_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searcharea',
            old_name='nw_long',
            new_name='nw_lon',
        ),
    ]
